### ISSUE TITLE
Publishing artifacts to MavenCentral

### ISSUE THREAD

**Issue by raiAtul** [linkedin/avro-util#137]
Hi,

We have seen a significant improvement in performance after using avro-fastserde, thank you for this amazing library.
I noticed that the artifacts are published to bintray which is on the deprecation path, I wanted to check if there are any plans to publish artifacts on any other repositories like MavenCentral.

Thanks,
Atul

**Comment by radai-rosenblatt** [comment]
I've published projects to maven central before and honestly find it too much of a pain to set up. we will be moving to https://linkedin.jfrog.io (a different service by the same company behind bintray)

**Comment by raiAtul** [comment]
Got it, thanks for the response.
Closing this issue.
