### ISSUE TITLE
Maven cannot resolve avroutil1:helper:0.2.32 dependency

### ISSUE THREAD

**Issue by narner90** [linkedin/avro-util#146]
I get the following error from Maven when including avro-codegen version 0.2.32:
```
Cannot resolve com.linkedin.avroutil1:helper:0.2.32
```

My dependency is specified as: 
```
<dependency>
    <groupId>com.linkedin.avroutil1</groupId>
    <artifactId>avro-codegen</artifactId>
    <version>0.2.32</version>
    <type>pom</type>
</dependency>
```

And the repository as:
```
<repository>
    <id>linkedin</id>
    <name>linkedin</name>
    <url>https://linkedin.bintray.com/maven/</url>
</repository>
```

Here is the relevant snippet from the avro-codegen POM that maven downloads. **Should `helper` be `helper-all` here?**
```
<dependency>
      <groupId>com.linkedin.avroutil1</groupId>
      <artifactId>helper</artifactId>
      <version>0.2.32</version>
      <scope>runtime</scope>
</dependency>
```

Thanks!

**Comment by radai-rosenblatt** [comment]
we do not publish the "thin" artifact.
have you tried helper-all ?

**Comment by narner90** [comment]
Thanks for the reply - `helper-all` works fine on its own for me.

I suspect it is the `avro-codegen` POM [bintray link](https://bintray.com/linkedin/maven/avro-util#files/com%2Flinkedin%2Favroutil1%2Favro-codegen%2F0.2.33) is the issue here, as it specifies `helper` rather than `helper-all` as a dependency.

**Comment by radai-rosenblatt** [comment]
you are correct. the pom produced for codegen (https://linkedin.jfrog.io/artifactory/avro-util/com/linkedin/avroutil1/avro-codegen/0.2.35/avro-codegen-0.2.35.pom) refers to helper and not helper-all.
i'll see what can be done to fix that

**Comment by radai-rosenblatt** [comment]
should be fixed now
