### ISSUE TITLE
when fixing up code generated by 1.9+, remove ref. to AvroMissingFieldException from builder build() methods

### ISSUE THREAD

**Issue by radai-rosenblatt** [linkedin/avro-util#151]
code generated under avro 1.9+ has a catch clause for AvroMissingFieldException in Builder.build() methods.
this exception class does not exist prior to 1.9 so generated code causes issues when run under avro < 1.9.

solution is to strip out the catch clause.

**Comment by kxu1026** [comment]
Thanks, Radai!
