### ISSUE TITLE
Provide version agnostic helper for fetching field properties

### ISSUE THREAD

**Issue by bobohu97** [linkedin/avro-util#160]
We need a version agnostic helper method to access the avro.JSONProperties of avro Schema and Field. That is, we need helper methods to get/add properties to Schema and Field i.e. addAllProps, getObjectProp, getObjectProps, getProp, hasProps (example given using avro 1.9.2 API). If it is too much to provide helpers for all these functions, for our current use case we could use any of the following avro version agnostic helper function that would:

1. get a list of property names
2. getProps
3. clone a record schema from another while preserving all the properties

**Comment by radai-rosenblatt** [comment]
between #162 and #163 im closing this
