### ISSUE TITLE
getSchemaPropAsJsonString returns JSON string with quotes. 

### ISSUE THREAD

**Issue by bobohu97** [linkedin/avro-util#165]
The API that `getSchemaPropAsJsonString` replaces (`getProp`) returns a JSON string without quotes, i.e. `{...}`. However, `getSchemaPropAsJsonString` is returning a string *with* quotes, i.e. `"{...}"`. The behavior of `getSchemaPropAsJsonString` should match `getProp` if possible. Thanks!

**Comment by radai-rosenblatt** [comment]
without explicitly quoting string values you would not be able to distinguish between "false" (a json string) and false (a json boolean), or similarly between "42" and 42.

while i understand this deviates from avro behavior i think its for the best. 
im willing to add a boolean flag to the getPropAsJsonString() methods to control quoting of string literals. if you want that - reopen this issue.
