### ISSUE TITLE
Expose a helper method to return default value as a Json string

### ISSUE THREAD

**Issue by Neenateresa** [linkedin/avro-util#195]
I want to compare the default values of a field between 2 avro schemas as a Json object. Can we add a helper method in AvroCompatibilityHelper to get the default value as a Json string?

Since `equals` implementation of GenericData.Record [type of object returned from getGenericDefaultValue ] also compares the schemas and field properties, equality based on the returned object from getGenericDefaultValue / getSpecificDefaultValue fails for default values of record type because the 2 schemas have some differences in the field properties [one of the schemas specifies an additional custom property].  We have a custom schema comparison logic for comparing the schemas that ignores those properties - so when comparing the default values, I only want to compare the field values [like when comparing as a Json] and not really the type information.

**Comment by radai-rosenblatt** [comment]
done. 0.2.48+
