### ISSUE TITLE
Issue with importing the lib

### ISSUE THREAD

**Issue by rish691** [linkedin/avro-util#25]
I tried adding the module (group: "com.linkedin.avroutil", name: "avro-fastserde", version:"0.1.5") in my gradle project. But the dependency doesn't resolve. I also tried out different version but doesn't help.

**Comment by radai-rosenblatt** [comment]
latest version (0.1.8) is available here - https://bintray.com/linkedin/maven/avro-util
that page also has instructions on how to add that repository to your build

**Comment by rish691** [comment]
Thanks!
