### ISSUE TITLE
[avro-fastserde] Support for avro 1.11.0

### ISSUE THREAD

**Issue by maciejkowalczyk** [linkedin/avro-util#261]
It seems #236/#237 are not enough for fast (de)serializers to be generated.

**Comment by maciejkowalczyk** [comment]
Since `AvroVersion.AVRO_1_11` is not included in `Utils.AVRO_VERSIONS_SUPPORTED_FOR_DESERIALIZER` fast reader and writer use regular avro implementation in 1.11.0.

**Comment by radai-rosenblatt** [comment]
thanks for finding this!
is it as simple as adding it to the support list ?
if so - could you file a PR from your fork?

**Comment by maciejkowalczyk** [comment]
I'm going to test it and will let you know.

**Comment by maciejkowalczyk** [comment]
It seems just enabling support was enough.
It is running on part of our production traffic without any issue or noticeable performance difference.
Also, in brief review of Avro 1.11 changes I couldn't find any that could harm fastserde
