### ISSUE TITLE
support setting field props in schema field builders

### ISSUE THREAD

**Issue by radai-rosenblatt** [linkedin/avro-util#383]

**Comment by i-ony** [comment]
[Coral](https://github.com/linkedin/coral) contains field builders that include props i.e: 

`private Schema.Field field(   String name,
  Schema schema,
  String doc,
  Object defaultValue,
  Map<String, Object> props )`

Currently, AvroCompatibilityHelper does not support this. 

We're trying to upgrade Coral to be compatible with Avro 1.10 so this is a possible issue
