### ISSUE TITLE
Avro 1.11.1 incorrectly detected as 1.10

### ISSUE THREAD

**Issue by amuraco** [linkedin/avro-util#385]
Looks like the version detection looking for 'record' in the list of RESERVED_WORDS in org.apache.avro.specific.SpecificData was changed in 1.11.1: https://issues.apache.org/jira/browse/AVRO-3305

**Comment by radai-rosenblatt** [comment]
the upstream PR added anew field TYPE_IDENTIFIER_RESERVED_WORDS - https://github.com/apache/avro/pull/1457/files
we could test for its existence before looking at the contents of  RESERVED_WORDS
