### ISSUE TITLE
0.2.143 not in Artifactory

### ISSUE THREAD

**Issue by cddude229** [linkedin/avro-util#458]
Hey, I was trying to upgrade to the latest release (https://github.com/linkedin/avro-util/releases/tag/0.2.143), but was getting build failures.  Our Artifactory couldn't find it, and when I poked around I noticed that https://linkedin.jfrog.io/ui/native/avro-util/com/linkedin/avroutil1/helper-all/ doesn't have it either (although it was 0.2.144-SNAPSHOT)

**Comment by FelixGV** [comment]
That's right... there's been a regression in the build that causes publishing to fail and to generate snapshots instead of proper releases... Currently, the latest proper release is [0.2.142](https://github.com/linkedin/avro-util/releases/tag/0.2.142).

**Comment by cddude229** [comment]
Got it - I misunderstood that release note as being a proper one. Thanks for the clarification.  (I'm ok with closing this unless this will be used to track the issue publicly)

**Comment by FelixGV** [comment]
Yeah we do care to fix this soon. I guess it's fine to keep it open.

**Comment by radai-rosenblatt** [comment]
im reverting the offending commit. any future work on fast-avro will need to properly clean the fast-avro build 1st - https://github.com/linkedin/avro-util/pull/460
