### ISSUE TITLE
avro-fastserde: No support for "avro.java.string" schema property.

### ISSUE THREAD

**Issue by flowenol** [linkedin/avro-util#58]
Hi,

The current implementation does not support the **avro.java.string** property which gives the ability to use plain java Strings in place of Utf8 wrappers. This is useful especially with specific record generated classes. This feature is very important for us and blocks the migration from the original avro-fastserde branch.  Below I have prepared a gist with an example test case that replicates the problem.

[test case](https://gist.github.com/flowenol/ba400ef0811f8fd7d98d80f0e71ad569)

**Comment by gaojieliu** [comment]
@flowenol 
The support of `avro.java.string` is added in this PR:
https://github.com/linkedin/avro-util/pull/62
Please take a look when you have time.

**Comment by gaojieliu** [comment]
Here  is  the latest PR:
https://github.com/linkedin/avro-util/pull/66

**Comment by gaojieliu** [comment]
@flowenol 
Please try this release, which includes `avro.java.string` schema property support:
https://bintray.com/linkedin/maven/avro-util/0.2.2
