### ISSUE TITLE
incompatible types: String cannot be converted to Utf8

### ISSUE THREAD

**Issue by izeye** [linkedin/avro-util#68]
Using `FastSpecificDatumWriter` throws the following errors:

```
/var/folders/wy/_4jkfljn7hbb5ltnzlm4jggh0000gn/T/generated10204258197036940757/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_8/User_SpecificSerializer_2352263923167790722.java:43: error: incompatible types: String cannot be converted to Utf8
            if (favorite_color0 instanceof Utf8) {
                ^
/var/folders/wy/_4jkfljn7hbb5ltnzlm4jggh0000gn/T/generated10204258197036940757/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_8/User_SpecificSerializer_2352263923167790722.java:44: error: incompatible types: String cannot be converted to Utf8
                (encoder).writeString(((Utf8) favorite_color0));
                                              ^
2 errors
23:52:59.819 [avro-fastserde-compile-thread-1] WARN com.linkedin.avro.fastserde.FastSerdeCache - Serializer class instantiation exception
com.linkedin.avro.fastserde.FastSerdeGeneratorException: com.linkedin.avro.fastserde.FastSerdeGeneratorException: Unable to compile:User_SpecificSerializer_2352263923167790722
	at com.linkedin.avro.fastserde.FastSerializerGenerator.generateSerializer(FastSerializerGenerator.java:87)
	at com.linkedin.avro.fastserde.FastSerdeCache.buildFastSpecificSerializer(FastSerdeCache.java:403)
	at com.linkedin.avro.fastserde.FastSerdeCache.buildSpecificSerializer(FastSerdeCache.java:410)
	at com.linkedin.avro.fastserde.FastSerdeCache.lambda$getFastSpecificSerializer$4(FastSerdeCache.java:260)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.linkedin.avro.fastserde.FastSerdeGeneratorException: Unable to compile:User_SpecificSerializer_2352263923167790722
	at com.linkedin.avro.fastserde.FastSerdeBase.compileClass(FastSerdeBase.java:135)
	at com.linkedin.avro.fastserde.FastSerializerGenerator.generateSerializer(FastSerializerGenerator.java:82)
	... 7 common frames omitted
```

Looking at the code, it seems that syntactically wrong code has been generated as follows:

```java
 40         String favorite_color0 = ((String) data.get(2));
 41         if (favorite_color0 instanceof String) {
 42             (encoder).writeIndex(0);
 43             if (favorite_color0 instanceof Utf8) {
 44                 (encoder).writeString(((Utf8) favorite_color0));
 45             } else {
 46                 (encoder).writeString(favorite_color0 .toString());
 47             }
 48         } else {
 49             if (favorite_color0 == null) {
 50                 (encoder).writeIndex(1);
 51                 (encoder).writeNull();
 52             }
 53         }
```

This is a test demonstrating the failure: https://github.com/izeye/samples-java-branches/blob/avro-util/src/test/java/learningtest/avro/UserTests.java#L136

**Comment by gaojieliu** [comment]
Hi @izeye 
I will investigate this  issue and will let  you if I have any update.

**Comment by gaojieliu** [comment]
Hi @izeye 
Could you share which avro-util version you were using?
I am using the latest release of avro-util, and I didn't see the issue you mentioned, and here is the generated  serializer in my env:
`public class User_SpecificSerializer_4190605954547771215
    implements FastSerializer<User>
{


    public void serialize(User data, Encoder encoder)
        throws IOException
    {
        serializeUser0(data, (encoder));
    }

    @SuppressWarnings("unchecked")
    public void serializeUser0(User data, Encoder encoder)
        throws IOException
    {
        if (data.get(0) instanceof Utf8) {
            (encoder).writeString(((Utf8) data.get(0)));
        } else {
            (encoder).writeString(data.get(0).toString());
        }
        Integer favorite_number0 = ((Integer) data.get(1));
        if (favorite_number0 instanceof Integer) {
            (encoder).writeIndex(0);
            (encoder).writeInt(((Integer) favorite_number0));
        } else {
            if (favorite_number0 == null) {
                (encoder).writeIndex(1);
                (encoder).writeNull();
            }
        }
        CharSequence favorite_color0 = ((CharSequence) data.get(2));
        if (favorite_color0 instanceof CharSequence) {
            (encoder).writeIndex(0);
            if (favorite_color0 instanceof Utf8) {
                (encoder).writeString(((Utf8) favorite_color0));
            } else {
                (encoder).writeString(favorite_color0 .toString());
            }
        } else {
            if (favorite_color0 == null) {
                (encoder).writeIndex(1);
                (encoder).writeNull();
            }
        }
    }

}`

**Comment by izeye** [comment]
@gaojieliu Thanks for the quick feedback!

The project I shared is using [the latest version (0.2.2) of `com.linkedin.avroutil1:avro-fastserde`](https://github.com/izeye/samples-java-branches/blob/avro-util/build.gradle#L74).

For your information, the test I shared can be run as follows:

```
$ git clone https://github.com/izeye/samples-java-branches.git
...
$ cd samples-java-branches/
$ git checkout avro-util 
...
$ ./gradlew clean test --tests UserTests.testWithoutSchemaViaFastSpecificDatumWriterFromLinkedIn
....
$
```

**Comment by SunwooKim** [comment]
Hi @gaojieliu, 

I'm not sure, PR #66  missed to handle `avro.java.string` at isStringable.

https://github.com/linkedin/avro-util/blob/7c40cfc555c7a4d4dac159305a193238642b077a/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java#L148-L158

- TO-BE 
```
return schema.getProp(CLASS_PROP) != null || schema.getProp(STRING_PROP) != null;
```

**Comment by gaojieliu** [comment]
Hi @SunwooKim,
I don't think it is related since the only place using `SchemaAssistant#isStringable` is in `FastSerializerGenerator#processString`, so at least it is  not related.
When trying in my local env, I realized your project requires Java 11, and all the tests I ran is using Java 8, so I think the issue might be caused by Java 11, and today avro-util is not supporting Java 11 properly, and there is another issue reported, which is related to Java 11:
https://github.com/linkedin/avro-util/issues/63

@izeye 
Could you try to run your  test in Java 8?

Thanks

**Comment by gaojieliu** [comment]
@izeye @SunwooKim 
Fix is here: https://github.com/linkedin/avro-util/pull/70
Please take a look if you have time.

**Comment by gaojieliu** [comment]
https://bintray.com/linkedin/maven/avro-util/0.2.3
Please try the above lib, and re-open this issue if you still encounter the same issue.

**Comment by izeye** [comment]
@gaojieliu I tried 0.2.3, but I'm still seeing the errors.

> re-open this issue

I can't reopen this as I don't have a permission to open it anymore.

**Comment by gaojieliu** [comment]
Hi @izeye 
That is very interesting...
Same error?

**Comment by izeye** [comment]
@gaojieliu Yes, it seems to be the same errors. You can reproduce it with the procedure I mentioned in https://github.com/linkedin/avro-util/issues/68#issuecomment-650449111.

**Comment by gaojieliu** [comment]
@izeye 
I think I understand what happened.
I will work on a proper fix.

**Comment by gaojieliu** [comment]
@izeye 
Please try the latest release:
https://bintray.com/linkedin/maven/avro-util/0.2.4

**Comment by izeye** [comment]
@gaojieliu Thanks for the fix! I confirmed that the errors have gone with 0.2.4.
