### ISSUE TITLE
fix sonarqube github action on commit

### ISSUE THREAD

**Issue by radai-rosenblatt** [linkedin/avro-util#98]
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> Could not find a default branch to fall back on.
`

from https://github.com/linkedin/avro-util/runs/1205858809

possible solution - https://community.sonarsource.com/t/sonar-maven-plugin-could-not-find-a-default-branch-to-fall-back-on/23973/11

**Comment by radai-rosenblatt** [comment]
dropped sonaqube

**Comment by NathanPB** [comment]
> dropped sonaqube

lmao

**Comment by Blunderchips** [comment]
Well, I guess this does technically solve the issue.
